//
// Created by LIONEL on 11/28/2025.
//

#ifndef IMPLEMENTASI_ALGORITMA_STRUKTUR_DATA__ALPRO_PANGKAT_H
#define IMPLEMENTASI_ALGORITMA_STRUKTUR_DATA__ALPRO_PANGKAT_H


class pangkat {
};


#endif //IMPLEMENTASI_ALGORITMA_STRUKTUR_DATA__ALPRO_PANGKAT_H