//
// Created by LIONEL on 11/28/2025.
//

#ifndef IMPLEMENTASI_ALGORITMA_STRUKTUR_DATA__ALPRO_SELECTION_H
#define IMPLEMENTASI_ALGORITMA_STRUKTUR_DATA__ALPRO_SELECTION_H


class selection {
};


#endif //IMPLEMENTASI_ALGORITMA_STRUKTUR_DATA__ALPRO_SELECTION_H